FROM python:3.12.1-slim-bullseye

WORKDIR /app

RUN pip install --no-cache-dir poetry

COPY pyproject.toml poetry.lock /app/

RUN poetry config virtualenvs.create false \
    && poetry install --no-root --no-dev

# Копируем оставшиеся файлы проекта
COPY ./bot/ /app/

ENV PYTHONUNBUFFERED=1

CMD ["python", "main.py"]
